# Generated by Django 4.2.23 on 2025-07-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_pk', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('followers', models.ManyToManyField(related_name='following_in_snapshots', to='instagram_automation.instagramuser')),
                ('following', models.ManyToManyField(related_name='followed_by_in_snapshots', to='instagram_automation.instagramuser')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='instagram_automation.instagramuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
